# Welcome to Jekyll!
#
# 基本信息
title: 阿辉的博客
email: lhhaini@gmail.com
description: 喜欢编码，爱折腾!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://handsomesboy.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
weibo_username: 啊D大吉大利
github_username: handsomesboy

# 文章目录格式化
permalink: /:year/:month/:day/:title/
# 文章摘要分隔符
excerpt_separator: "\n\n\n\n"

# 评论组件
disqus_shortname: tomoya

# statistic analysis 统计代码
baidu_tongji_id: ea48aecd7a280d09dcb0d1074c42021f
google_analytics_id: UAAAAAAA

# webmaster meta
bing_meta: 8D00F36D8929A335207FBCE7F13C50B3

# 格式化文档
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 开启相关文章功能，可惜github pages不支持
# lsi: true

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# 分页
paginate: 10

# 搜索服务
algolia:
  application_id: "36883FPR2D"
  index_name: "36883FPR2D"
  search_only_api_key: "2d40767987f704b3b04b9efce7ff49c8"

# 友情链接
links:
  - name: 百度
    url: https://baidu.com/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
